language: python
sudo: false
cache: pip

matrix:
  include:
    - python: 2.7

git:
  depth: 1

install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install flake8

script:
  - coverage run scripts/oe.py
  - flake8 scripts/oe.py
  - pytest

after_success:
  - codecov
  - coveralls
