language: python
sudo: false
cache: pip

python:
  - "2.7"

git:
  depth: 1

install:
  - pip install codecov
  - pip install flake8
script:
  - python tests/test_oe.py
  - coverage run scripts
  - flake8 scripts/ --max-line-length=80

after_success:
  - codecov

