language: python
cache: pip

matrix:
  include:
#    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - nightly

git:
  depth: 1

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install flake8
  - pip install coveralls
  - pip install codecov

script:
  - flake8 scripts/sd.py
  - flake8 scripts/oe.py
  - pytest --cov=./

after_success:
  - codecov
  - coveralls
