language: python
sudo: false
cache: pip

python:
  - "2.7"

git:
  depth: 1

install:
  - pip install codecov

script:
  - python tests/test_oe.py
  - coverage run scripts

after_success:
  - codecov

