language: python
sudo: false
cache: pip

python:
  - "2.7"

git:
  depth: 1

install:
  - pip install codecov
  - pip install flake8

script:
  - python scripts/test_oe.py
  - coverage run scripts/oe.py
  - flake8 scripts/test_oe.py

after_success:
  - codecov
  - coveralls
