language: python
sudo: false
cache: pip

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

git:
  depth: 1

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install flake8

script:
  - pytest --cov=./
  - flake8 scripts/sd.py
  - flake8 scripts/oe.py
  - pytest

after_success:
  - codecov
  - coveralls
